### ISSUE TITLE
Make sure every ENV_VAR maps to an --explicit-flag

### ISSUE THREAD

**Issue by peterbourgon** [unikraft/kraftkit#1246]
### Feature request summary

As a user, I should be able to specify any configuration parameter as either an ENV_VAR or an --explicit-flag. 

As an example, I should be able to specify a Kraft Cloud token as either

```
env KRAFTCLOUD_TOKEN=xxx kraft cloud ...
```

or 

```
kraft cloud --token=xxx ...
```

This ensures that `-h, --help` reliably describes the complete configuration "surface area" of the program. It also means I don't need to split configuration parameters across explicit/visible flags passed to `kraft`, and implicit/invisible env vars taken from the session.

### Related architectures

None

### Related platforms

None

**Comment by nderjung** [comment]
Hey @peterbourgon, this makes sense.  The `KRAFTCLOUD_TOKEN` env var was a special variable which we introduced since it's use is slightly different in the context of our CLI factory; that said, all other flags are also env vars and operate in the same way as-per your suggested method.

I can work in a fix that ensures `KRAFTCLOUD_TOKEN` is supported by a `--token` flag.
