### ISSUE TITLE
Kraftfile: `--no-cache` is required to fetch from a different `source`

### ISSUE THREAD

**Issue by ls-1801** [unikraft/kraftkit#248]
### Describe the bug

Specifying an alternative source within the Kraftfile only works if the `--no-cache` CLI option is used.
```yaml
unikraft:
  source: https://github.com/ls-1801/unikraft.git
  version: staging
  kconfig:
    - [...]
```

### Steps to reproduce
try to use an alternative source without the `--no-cache` option

```yaml
unikraft:
  source: https://github.com/ls-1801/unikraft.git
```

### Expected behavior

The alternative source is cached and updated if the latest commit hash changes.

### Relevant log output
With `--no-cache`
```
kraft pkg pull --log-level debug  --no-cache
 D  querying manifest catalog cache=false name=unikraft source=https://github.com/ls-1801/unikraft.git types=[core] version=staging
 i  probing https://github.com/ls-1801/unikraft.git
 D  found 1 manifests in catalog
```

Without `--no-cache`
```
kraft pkg pull --log-level debug 
 D  querying manifest catalog cache=true name=unikraft source=https://github.com/ls-1801/unikraft.git types=[core] version=staging
 D  found 80 manifests in catalog
 W  could not find core-unikraft:staging
```

**Comment by craciunoiuc** [comment]
Hey @ls-1801,

I think your issue is describing three different problems:

 - kraftkit should update the local cache when new commits come in
 - the build/pull folder should update itself by pulling the latest changes on subsequent runs
 - the caching system should support forks of repos

For what you are trying to do, `--no-cache` just means "ignore the cache completely", so it should be fine.
A manual approach would be to clear the old cache from `~/.local/share/kraftkit/sources` once you want to replace a repository with a fork.

**Comment by craciunoiuc** [comment]
Caching is now ignored when using link sources in kraftfiles.
