### ISSUE TITLE
Version number format for libraries doesn't work

### ISSUE THREAD

**Issue by gabrielmocanu** [unikraft/kraftkit#561]
### Describe the bug

The build process failed to find libraries if they have a version number in the `kraft.yml` file instead of `stable` even though the version number is valid.

### Steps to reproduce

```bash
git clone --depth=1 https://github.com/unikraft/app-nginx.git;
cd app-nginx;
# Modify the `kraft.yml` file and change `stable` version for `musl` to version number format( e.g. "0.11.0")
# I checked version number and it exists in the manifest file of `kraftkit`
kraft build --plat qemu --arch x86_64;
# It will end up like this
```
![image](https://github.com/unikraft/kraftkit/assets/34304856/e52c3beb-b902-4ff3-826a-7d42f91ca8bf)

The same it's happens with `app-helloworld-go`.

### Expected behavior

The build process should run without any issues.

### Which architectures were you using or does this bug affect?

x86_64

### Which operating system were you using or does this bug affect?

linux/debian

**Comment by craciunoiuc** [comment]
This happens because it matches on the `version:` field

For example, this is an entry for unikraft:
```yaml
- resource: https://github.com/unikraft/unikraft/archive/2017e3f.tar.gz
  type: gitsha
  unikraft: 0.13.0
  version: 2017e3f
```
if you try to use this it will fail:
```yaml
unikraft:
  version: 0.13.0
```

but if you try to use this it will work:
```yaml
unikraft:
  version: 2017e3f
```

@nderjung is this a bug or intended? Sounds like a bug :sweat_smile:

**Comment by nderjung** [comment]
This addition (#567)  means that both the Unikraft version and the library's version are possible in the `version` attribute of the `Kraftfile`.

I fear this has an unintended consequence. Specifying the version based on Unikraft, in my opinion, should not be used as the library's version. This can create a confusion between when a library's version is the same as the Unikraft version.

Whilst not yet implemented, [the versioning WG track on the Unikraft core](https://docs.google.com/document/d/1A-CAss5RvgYapg3YO8GNCdMki6cgq_7XG5om8nVWWGk/edit) aims to enable passing the actual origin library's specific version.  When an origin library and Unikraft both have a same version, kraftkit will not know which to select, or will select the origin library's version -- since it is the first to be checked in the sequence this modifies.

The used attribute Unikraft is meant to be an indicator of the minimum version of Unikraft that the library supports at `version`. 

It was possible to do this originally with pykraft, which is why some of the older app-* repos have the Unikraft version, but it was not possible with KraftKit.
