### ISSUE TITLE
`kraft build` does not configure the application properly if the app is not on one of `unikraft` organisation branches

### ISSUE THREAD

**Issue by StefanJum** [unikraft/kraftkit#645]
### Describe the bug

Running `kraft build` from a repository while checked out on a branch that is not part of the `unikraft` organisation (e.g. fetching to a pull request) will cause the configuration to not add external libraries from `kraft.yaml`.

For example:

```console
$ git clone https://github.com/unikraft/app-helloworld-cpp
$ cd app-helloworld-cpp/
$ gh pr checkout 13 # this will checkout on another branch
$ kraft build

[...]

$ cat .config.helloworld-cpp_qemu-x86_64 | grep -i libcxx
# CONFIG_LIBCXXABI is not set
# CONFIG_LIBCXX is not set
```

The `libcxx` and `libcxxabi` libraries are present in the `kraft.yaml` file.
Also for whatever reason the `musl` library gets selected, but not any other.

**Comment by craciunoiuc** [comment]
This issue is caused by two issues:
 * `musl` is [hardcoded first](https://github.com/unikraft/kraftkit/blob/staging/unikraft/app/application.go#L351) because of an older bug. The actual order for `app-helloworld-cpp` is `LIBS := $(UK_LIBS)/libcxxabi:$(UK_LIBS)/libcxx:$(UK_LIBS)/compiler-rt:$(UK_LIBS)/libunwind:$(UK_LIBS)/musl`
  * libraries that begin with `lib` are currently not being selected correctly. This is because they are named `lib*`, but their symbol does not have the starting `LIB` (`CONFIG_LIBUUID`, instead of `CONFIG_LIBLIBUUID`).
